fix: uninstall go-bindata before go
to fix issues like this:

Error: Refusing to uninstall /opt/homebrew/Cellar/go/1.23.2
because it is required by go-bindata, which is currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies golang